server:
  port: 8189

network: mainnet

chains: [Ethereum,Cosmos]

wallet_node:
  eth:
    rpcs:
      - rpc_url: 'https://rpc.flashbots.net'
    confirmations: 4
    data_api_url: 'https://api.etherscan.io/api?'
    data_api_key: 'HZEZGEPJJDA633N421AYW9NE8JFNZZC7JT'
    data_api_token: ''
    time_out: 100
  cosmos:
    rpcs:
      - rpc_url: 'https://cosmos-rpc.publicnode.com:443'
    rest_url: 'https://cosmos-rest.publicnode.com/'
    confirmations: 4
    data_api_url: 'https://api.etherscan.io/api?'
    data_api_key: 'HZEZGEPJJDA633N421AYW9NE8JFNZZC7JT'
    data_api_token: ''
    time_out: 100
